// AUTO-GENERATED by `npx supabase gen types typescript --project-id loqhpykkovwczdckekju --schema public` — do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      claims: {
        Row: {
          canonical_claim_en: string | null
          canonical_claim_ko: string | null
          claim_category: string
          claim_code: string | null
          claim_key: string | null
          claim_name_en: string | null
          claim_name_ko: string
          claim_scope: string
          claim_subject_en: string | null
          claim_subject_ko: string | null
          created_at: string
          description: string | null
          id: number
          predicate_type: string | null
          source_language: string
          updated_at: string
        }
        Insert: {
          canonical_claim_en?: string | null
          canonical_claim_ko?: string | null
          claim_category: string
          claim_code?: string | null
          claim_key?: string | null
          claim_name_en?: string | null
          claim_name_ko: string
          claim_scope: string
          claim_subject_en?: string | null
          claim_subject_ko?: string | null
          created_at?: string
          description?: string | null
          id?: number
          predicate_type?: string | null
          source_language?: string
          updated_at?: string
        }
        Update: {
          canonical_claim_en?: string | null
          canonical_claim_ko?: string | null
          claim_category?: string
          claim_code?: string | null
          claim_key?: string | null
          claim_name_en?: string | null
          claim_name_ko?: string
          claim_scope?: string
          claim_subject_en?: string | null
          claim_subject_ko?: string | null
          created_at?: string
          description?: string | null
          id?: number
          predicate_type?: string | null
          source_language?: string
          updated_at?: string
        }
        Relationships: []
      }
      code_tables: {
        Row: {
          created_at: string
          description: string | null
          id: number
          table_code: string
          table_name_en: string | null
          table_name_ko: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: number
          table_code: string
          table_name_en?: string | null
          table_name_ko: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: number
          table_code?: string
          table_name_en?: string | null
          table_name_ko?: string
        }
        Relationships: []
      }
      code_values: {
        Row: {
          code: string
          code_table_id: number
          created_at: string
          id: number
          is_active: boolean
          label_en: string | null
          label_ko: string
          sort_order: number | null
        }
        Insert: {
          code: string
          code_table_id: number
          created_at?: string
          id?: number
          is_active?: boolean
          label_en?: string | null
          label_ko: string
          sort_order?: number | null
        }
        Update: {
          code?: string
          code_table_id?: number
          created_at?: string
          id?: number
          is_active?: boolean
          label_en?: string | null
          label_ko?: string
          sort_order?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "code_values_code_table_id_fkey"
            columns: ["code_table_id"]
            isOneToOne: false
            referencedRelation: "code_tables"
            referencedColumns: ["id"]
          },
        ]
      }
      collection_jobs: {
        Row: {
          created_at: string
          entity_type: string
          error_message: string | null
          finished_at: string | null
          id: number
          job_name: string
          job_type: string
          priority: string | null
          query_payload: Json | null
          retry_count: number
          scheduled_at: string | null
          source_connector_id: number
          started_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          entity_type: string
          error_message?: string | null
          finished_at?: string | null
          id?: number
          job_name: string
          job_type: string
          priority?: string | null
          query_payload?: Json | null
          retry_count?: number
          scheduled_at?: string | null
          source_connector_id: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          entity_type?: string
          error_message?: string | null
          finished_at?: string | null
          id?: number
          job_name?: string
          job_type?: string
          priority?: string | null
          query_payload?: Json | null
          retry_count?: number
          scheduled_at?: string | null
          source_connector_id?: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "collection_jobs_source_connector_id_fkey"
            columns: ["source_connector_id"]
            isOneToOne: false
            referencedRelation: "source_connectors"
            referencedColumns: ["id"]
          },
        ]
      }
      collection_runs: {
        Row: {
          collection_job_id: number
          error_details: Json | null
          execution_log: string | null
          finished_at: string | null
          id: number
          records_created: number | null
          records_failed: number | null
          records_fetched: number | null
          records_unchanged: number | null
          records_updated: number | null
          run_status: string
          started_at: string
        }
        Insert: {
          collection_job_id: number
          error_details?: Json | null
          execution_log?: string | null
          finished_at?: string | null
          id?: number
          records_created?: number | null
          records_failed?: number | null
          records_fetched?: number | null
          records_unchanged?: number | null
          records_updated?: number | null
          run_status: string
          started_at?: string
        }
        Update: {
          collection_job_id?: number
          error_details?: Json | null
          execution_log?: string | null
          finished_at?: string | null
          id?: number
          records_created?: number | null
          records_failed?: number | null
          records_fetched?: number | null
          records_unchanged?: number | null
          records_updated?: number | null
          run_status?: string
          started_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "collection_runs_collection_job_id_fkey"
            columns: ["collection_job_id"]
            isOneToOne: false
            referencedRelation: "collection_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      dosage_guidelines: {
        Row: {
          created_at: string
          dose_max: number | null
          dose_min: number | null
          dose_unit: string | null
          frequency_text: string | null
          id: number
          indication_context: string | null
          ingredient_id: number
          notes: string | null
          population_group: string
          recommendation_type: string | null
          route: string | null
          source_id: number | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          dose_max?: number | null
          dose_min?: number | null
          dose_unit?: string | null
          frequency_text?: string | null
          id?: number
          indication_context?: string | null
          ingredient_id: number
          notes?: string | null
          population_group: string
          recommendation_type?: string | null
          route?: string | null
          source_id?: number | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          dose_max?: number | null
          dose_min?: number | null
          dose_unit?: string | null
          frequency_text?: string | null
          id?: number
          indication_context?: string | null
          ingredient_id?: number
          notes?: string | null
          population_group?: string
          recommendation_type?: string | null
          route?: string | null
          source_id?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "dosage_guidelines_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_dosage_guidelines_source"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      entity_refresh_states: {
        Row: {
          entity_id: number
          entity_type: string
          external_id: string | null
          id: number
          last_changed_at: string | null
          last_checksum: string | null
          last_fetched_at: string | null
          last_refresh_status: string | null
          next_scheduled_refresh_at: string | null
          refresh_priority: string | null
          source_connector_id: number | null
        }
        Insert: {
          entity_id: number
          entity_type: string
          external_id?: string | null
          id?: number
          last_changed_at?: string | null
          last_checksum?: string | null
          last_fetched_at?: string | null
          last_refresh_status?: string | null
          next_scheduled_refresh_at?: string | null
          refresh_priority?: string | null
          source_connector_id?: number | null
        }
        Update: {
          entity_id?: number
          entity_type?: string
          external_id?: string | null
          id?: number
          last_changed_at?: string | null
          last_checksum?: string | null
          last_fetched_at?: string | null
          last_refresh_status?: string | null
          next_scheduled_refresh_at?: string | null
          refresh_priority?: string | null
          source_connector_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "entity_refresh_states_source_connector_id_fkey"
            columns: ["source_connector_id"]
            isOneToOne: false
            referencedRelation: "source_connectors"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_grade_history: {
        Row: {
          change_reason: string | null
          changed_at: string
          changed_by: string | null
          claim_id: number
          id: number
          ingredient_id: number
          new_grade: string | null
          old_grade: string | null
        }
        Insert: {
          change_reason?: string | null
          changed_at?: string
          changed_by?: string | null
          claim_id: number
          id?: number
          ingredient_id: number
          new_grade?: string | null
          old_grade?: string | null
        }
        Update: {
          change_reason?: string | null
          changed_at?: string
          changed_by?: string | null
          claim_id?: number
          id?: number
          ingredient_id?: number
          new_grade?: string | null
          old_grade?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "evidence_grade_history_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_grade_history_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_outcomes: {
        Row: {
          adverse_event_summary: string | null
          claim_id: number | null
          conclusion_summary: string | null
          confidence_interval_text: string | null
          created_at: string
          effect_direction: string | null
          effect_size_text: string | null
          evidence_study_id: number
          id: number
          outcome_name: string
          outcome_type: string | null
          p_value_text: string | null
          updated_at: string
        }
        Insert: {
          adverse_event_summary?: string | null
          claim_id?: number | null
          conclusion_summary?: string | null
          confidence_interval_text?: string | null
          created_at?: string
          effect_direction?: string | null
          effect_size_text?: string | null
          evidence_study_id: number
          id?: number
          outcome_name: string
          outcome_type?: string | null
          p_value_text?: string | null
          updated_at?: string
        }
        Update: {
          adverse_event_summary?: string | null
          claim_id?: number | null
          conclusion_summary?: string | null
          confidence_interval_text?: string | null
          created_at?: string
          effect_direction?: string | null
          effect_size_text?: string | null
          evidence_study_id?: number
          id?: number
          outcome_name?: string
          outcome_type?: string | null
          p_value_text?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_outcomes_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_outcomes_evidence_study_id_fkey"
            columns: ["evidence_study_id"]
            isOneToOne: false
            referencedRelation: "evidence_studies"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_studies: {
        Row: {
          abstract_text: string | null
          authors: string | null
          comparator_text: string | null
          created_at: string
          doi: string | null
          duplicate_group_key: string | null
          duration_text: string | null
          external_url: string | null
          id: number
          included_in_summary: boolean
          ingredient_id: number
          journal_name: string | null
          overall_relevance_score: number | null
          pmid: string | null
          population_text: string | null
          publication_date: string | null
          publication_year: number | null
          risk_of_bias: string | null
          sample_size: number | null
          screening_status: string | null
          source_type: string
          study_design: string | null
          title: string
          updated_at: string
        }
        Insert: {
          abstract_text?: string | null
          authors?: string | null
          comparator_text?: string | null
          created_at?: string
          doi?: string | null
          duplicate_group_key?: string | null
          duration_text?: string | null
          external_url?: string | null
          id?: number
          included_in_summary?: boolean
          ingredient_id: number
          journal_name?: string | null
          overall_relevance_score?: number | null
          pmid?: string | null
          population_text?: string | null
          publication_date?: string | null
          publication_year?: number | null
          risk_of_bias?: string | null
          sample_size?: number | null
          screening_status?: string | null
          source_type: string
          study_design?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          abstract_text?: string | null
          authors?: string | null
          comparator_text?: string | null
          created_at?: string
          doi?: string | null
          duplicate_group_key?: string | null
          duration_text?: string | null
          external_url?: string | null
          id?: number
          included_in_summary?: boolean
          ingredient_id?: number
          journal_name?: string | null
          overall_relevance_score?: number | null
          pmid?: string | null
          population_text?: string | null
          publication_date?: string | null
          publication_year?: number | null
          risk_of_bias?: string | null
          sample_size?: number | null
          screening_status?: string | null
          source_type?: string
          study_design?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_studies_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      extraction_results: {
        Row: {
          confidence_score: number | null
          created_at: string
          extracted_fields: Json
          extraction_method: string
          extraction_version: string
          id: number
          needs_review: boolean
          raw_document_id: number
          schema_version: string
        }
        Insert: {
          confidence_score?: number | null
          created_at?: string
          extracted_fields: Json
          extraction_method: string
          extraction_version: string
          id?: number
          needs_review?: boolean
          raw_document_id: number
          schema_version: string
        }
        Update: {
          confidence_score?: number | null
          created_at?: string
          extracted_fields?: Json
          extraction_method?: string
          extraction_version?: string
          id?: number
          needs_review?: boolean
          raw_document_id?: number
          schema_version?: string
        }
        Relationships: [
          {
            foreignKeyName: "extraction_results_raw_document_id_fkey"
            columns: ["raw_document_id"]
            isOneToOne: false
            referencedRelation: "raw_documents"
            referencedColumns: ["id"]
          },
        ]
      }
      ingredient_claims: {
        Row: {
          allowed_expression: string | null
          approval_country_code: string | null
          claim_id: number
          claim_scope_note: string | null
          created_at: string
          evidence_grade: string | null
          evidence_grade_text: string | null
          evidence_summary: string | null
          id: number
          ingredient_id: number
          is_regulator_approved: boolean
          prohibited_expression: string | null
          raw_claim_language: string
          raw_claim_text: string | null
          recognition_no: string | null
          source_dataset: string | null
          source_priority: number | null
          updated_at: string
        }
        Insert: {
          allowed_expression?: string | null
          approval_country_code?: string | null
          claim_id: number
          claim_scope_note?: string | null
          created_at?: string
          evidence_grade?: string | null
          evidence_grade_text?: string | null
          evidence_summary?: string | null
          id?: number
          ingredient_id: number
          is_regulator_approved?: boolean
          prohibited_expression?: string | null
          raw_claim_language?: string
          raw_claim_text?: string | null
          recognition_no?: string | null
          source_dataset?: string | null
          source_priority?: number | null
          updated_at?: string
        }
        Update: {
          allowed_expression?: string | null
          approval_country_code?: string | null
          claim_id?: number
          claim_scope_note?: string | null
          created_at?: string
          evidence_grade?: string | null
          evidence_grade_text?: string | null
          evidence_summary?: string | null
          id?: number
          ingredient_id?: number
          is_regulator_approved?: boolean
          prohibited_expression?: string | null
          raw_claim_language?: string
          raw_claim_text?: string | null
          recognition_no?: string | null
          source_dataset?: string | null
          source_priority?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ingredient_claims_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ingredient_claims_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      ingredient_drug_interactions: {
        Row: {
          clinical_effect: string | null
          created_at: string
          drug_class: string | null
          drug_name: string
          evidence_level: string | null
          id: number
          ingredient_id: number
          interaction_mechanism: string | null
          recommendation: string | null
          severity_level: string | null
          source_id: number | null
          updated_at: string
        }
        Insert: {
          clinical_effect?: string | null
          created_at?: string
          drug_class?: string | null
          drug_name: string
          evidence_level?: string | null
          id?: number
          ingredient_id: number
          interaction_mechanism?: string | null
          recommendation?: string | null
          severity_level?: string | null
          source_id?: number | null
          updated_at?: string
        }
        Update: {
          clinical_effect?: string | null
          created_at?: string
          drug_class?: string | null
          drug_name?: string
          evidence_level?: string | null
          id?: number
          ingredient_id?: number
          interaction_mechanism?: string | null
          recommendation?: string | null
          severity_level?: string | null
          source_id?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fk_drug_interactions_source"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ingredient_drug_interactions_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      ingredient_search_documents: {
        Row: {
          ingredient_id: number
          search_text: string
          search_vector: unknown
          updated_at: string
        }
        Insert: {
          ingredient_id: number
          search_text: string
          search_vector?: unknown
          updated_at?: string
        }
        Update: {
          ingredient_id?: number
          search_text?: string
          search_vector?: unknown
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ingredient_search_documents_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: true
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      ingredient_synonyms: {
        Row: {
          created_at: string
          id: number
          ingredient_id: number
          is_preferred: boolean
          language_code: string | null
          synonym: string
          synonym_type: string
        }
        Insert: {
          created_at?: string
          id?: number
          ingredient_id: number
          is_preferred?: boolean
          language_code?: string | null
          synonym: string
          synonym_type: string
        }
        Update: {
          created_at?: string
          id?: number
          ingredient_id?: number
          is_preferred?: boolean
          language_code?: string | null
          synonym?: string
          synonym_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "ingredient_synonyms_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      ingredients: {
        Row: {
          canonical_name_en: string | null
          canonical_name_ko: string
          created_at: string
          description: string | null
          display_name: string | null
          form_description: string | null
          id: number
          ingredient_type: string
          is_active: boolean
          is_published: boolean
          last_reviewed_at: string | null
          last_synced_at: string | null
          origin_type: string | null
          parent_ingredient_id: number | null
          scientific_name: string | null
          slug: string | null
          standardization_info: string | null
          updated_at: string
        }
        Insert: {
          canonical_name_en?: string | null
          canonical_name_ko: string
          created_at?: string
          description?: string | null
          display_name?: string | null
          form_description?: string | null
          id?: number
          ingredient_type: string
          is_active?: boolean
          is_published?: boolean
          last_reviewed_at?: string | null
          last_synced_at?: string | null
          origin_type?: string | null
          parent_ingredient_id?: number | null
          scientific_name?: string | null
          slug?: string | null
          standardization_info?: string | null
          updated_at?: string
        }
        Update: {
          canonical_name_en?: string | null
          canonical_name_ko?: string
          created_at?: string
          description?: string | null
          display_name?: string | null
          form_description?: string | null
          id?: number
          ingredient_type?: string
          is_active?: boolean
          is_published?: boolean
          last_reviewed_at?: string | null
          last_synced_at?: string | null
          origin_type?: string | null
          parent_ingredient_id?: number | null
          scientific_name?: string | null
          slug?: string | null
          standardization_info?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ingredients_parent_ingredient_id_fkey"
            columns: ["parent_ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      label_snapshots: {
        Row: {
          captured_at: string | null
          created_at: string
          directions_text: string | null
          effective_date: string | null
          id: number
          is_current: boolean
          label_version: string | null
          product_id: number
          raw_label_text: string | null
          serving_size_text: string | null
          servings_per_container: string | null
          source_name: string | null
          source_url: string | null
          storage_text: string | null
          updated_at: string
          warning_text: string | null
        }
        Insert: {
          captured_at?: string | null
          created_at?: string
          directions_text?: string | null
          effective_date?: string | null
          id?: number
          is_current?: boolean
          label_version?: string | null
          product_id: number
          raw_label_text?: string | null
          serving_size_text?: string | null
          servings_per_container?: string | null
          source_name?: string | null
          source_url?: string | null
          storage_text?: string | null
          updated_at?: string
          warning_text?: string | null
        }
        Update: {
          captured_at?: string | null
          created_at?: string
          directions_text?: string | null
          effective_date?: string | null
          id?: number
          is_current?: boolean
          label_version?: string | null
          product_id?: number
          raw_label_text?: string | null
          serving_size_text?: string | null
          servings_per_container?: string | null
          source_name?: string | null
          source_url?: string | null
          storage_text?: string | null
          updated_at?: string
          warning_text?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "label_snapshots_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_aliases: {
        Row: {
          alias: string
          alias_type: string
          confidence: number | null
          created_at: string
          id: number
          language_code: string | null
          product_id: number
          source: string | null
          updated_at: string
        }
        Insert: {
          alias: string
          alias_type: string
          confidence?: number | null
          created_at?: string
          id?: number
          language_code?: string | null
          product_id: number
          source?: string | null
          updated_at?: string
        }
        Update: {
          alias?: string
          alias_type?: string
          confidence?: number | null
          created_at?: string
          id?: number
          language_code?: string | null
          product_id?: number
          source?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_aliases_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_enrichment_queue: {
        Row: {
          attempts: number
          completed_at: string | null
          created_at: string
          id: number
          last_error: string | null
          matched_report_no: string | null
          payload: Json | null
          product_id: number
          scheduled_for: string
          source: string | null
          status: string
          updated_at: string
        }
        Insert: {
          attempts?: number
          completed_at?: string | null
          created_at?: string
          id?: number
          last_error?: string | null
          matched_report_no?: string | null
          payload?: Json | null
          product_id: number
          scheduled_for?: string
          source?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          attempts?: number
          completed_at?: string | null
          created_at?: string
          id?: number
          last_error?: string | null
          matched_report_no?: string | null
          payload?: Json | null
          product_id?: number
          scheduled_for?: string
          source?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_enrichment_queue_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: true
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_images: {
        Row: {
          captured_at: string
          created_at: string
          height: number | null
          id: number
          image_hash: string | null
          is_primary: boolean
          mime_type: string | null
          product_id: number
          r2_key: string | null
          r2_public_url: string | null
          removed_at: string | null
          size_bytes: number | null
          source: string
          source_url: string | null
          updated_at: string
          width: number | null
        }
        Insert: {
          captured_at?: string
          created_at?: string
          height?: number | null
          id?: number
          image_hash?: string | null
          is_primary?: boolean
          mime_type?: string | null
          product_id: number
          r2_key?: string | null
          r2_public_url?: string | null
          removed_at?: string | null
          size_bytes?: number | null
          source: string
          source_url?: string | null
          updated_at?: string
          width?: number | null
        }
        Update: {
          captured_at?: string
          created_at?: string
          height?: number | null
          id?: number
          image_hash?: string | null
          is_primary?: boolean
          mime_type?: string | null
          product_id?: number
          r2_key?: string | null
          r2_public_url?: string | null
          removed_at?: string | null
          size_bytes?: number | null
          source?: string
          source_url?: string | null
          updated_at?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_ingredients: {
        Row: {
          amount_per_serving: number | null
          amount_unit: string | null
          created_at: string
          daily_amount: number | null
          daily_amount_unit: string | null
          id: number
          ingredient_id: number
          ingredient_role: string | null
          is_standardized: boolean | null
          product_id: number
          raw_label_name: string | null
          standardization_text: string | null
          updated_at: string
        }
        Insert: {
          amount_per_serving?: number | null
          amount_unit?: string | null
          created_at?: string
          daily_amount?: number | null
          daily_amount_unit?: string | null
          id?: number
          ingredient_id: number
          ingredient_role?: string | null
          is_standardized?: boolean | null
          product_id: number
          raw_label_name?: string | null
          standardization_text?: string | null
          updated_at?: string
        }
        Update: {
          amount_per_serving?: number | null
          amount_unit?: string | null
          created_at?: string
          daily_amount?: number | null
          daily_amount_unit?: string | null
          id?: number
          ingredient_id?: number
          ingredient_role?: string | null
          is_standardized?: boolean | null
          product_id?: number
          raw_label_name?: string | null
          standardization_text?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_ingredients_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_ingredients_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          approval_or_report_no: string | null
          barcode: string | null
          brand_name: string | null
          country_code: string | null
          created_at: string
          distributor_name: string | null
          id: number
          is_published: boolean
          manufacturer_name: string | null
          marketplace_category: string | null
          official_url: string | null
          product_image_url: string | null
          product_name: string
          product_type: string | null
          sale_channel: string | null
          sale_url: string | null
          sale_verified_at: string | null
          status: string | null
          updated_at: string
        }
        Insert: {
          approval_or_report_no?: string | null
          barcode?: string | null
          brand_name?: string | null
          country_code?: string | null
          created_at?: string
          distributor_name?: string | null
          id?: number
          is_published?: boolean
          manufacturer_name?: string | null
          marketplace_category?: string | null
          official_url?: string | null
          product_image_url?: string | null
          product_name: string
          product_type?: string | null
          sale_channel?: string | null
          sale_url?: string | null
          sale_verified_at?: string | null
          status?: string | null
          updated_at?: string
        }
        Update: {
          approval_or_report_no?: string | null
          barcode?: string | null
          brand_name?: string | null
          country_code?: string | null
          created_at?: string
          distributor_name?: string | null
          id?: number
          is_published?: boolean
          manufacturer_name?: string | null
          marketplace_category?: string | null
          official_url?: string | null
          product_image_url?: string | null
          product_name?: string
          product_type?: string | null
          sale_channel?: string | null
          sale_url?: string | null
          sale_verified_at?: string | null
          status?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      raw_documents: {
        Row: {
          checksum: string | null
          content_type: string | null
          created_at: string
          entity_external_id: string | null
          entity_type: string
          fetched_at: string
          file_path: string | null
          html_snapshot_path: string | null
          id: number
          raw_json: Json | null
          raw_text: string | null
          screenshot_path: string | null
          source_connector_id: number
          source_url: string | null
        }
        Insert: {
          checksum?: string | null
          content_type?: string | null
          created_at?: string
          entity_external_id?: string | null
          entity_type: string
          fetched_at?: string
          file_path?: string | null
          html_snapshot_path?: string | null
          id?: number
          raw_json?: Json | null
          raw_text?: string | null
          screenshot_path?: string | null
          source_connector_id: number
          source_url?: string | null
        }
        Update: {
          checksum?: string | null
          content_type?: string | null
          created_at?: string
          entity_external_id?: string | null
          entity_type?: string
          fetched_at?: string
          file_path?: string | null
          html_snapshot_path?: string | null
          id?: number
          raw_json?: Json | null
          raw_text?: string | null
          screenshot_path?: string | null
          source_connector_id?: number
          source_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "raw_documents_source_connector_id_fkey"
            columns: ["source_connector_id"]
            isOneToOne: false
            referencedRelation: "source_connectors"
            referencedColumns: ["id"]
          },
        ]
      }
      refresh_policies: {
        Row: {
          change_detection_method: string | null
          created_at: string
          entity_type: string
          full_sync_cron: string | null
          id: number
          incremental_sync_cron: string | null
          is_active: boolean
          refresh_mode: string
          source_connector_id: number | null
          staleness_days: number | null
          updated_at: string
        }
        Insert: {
          change_detection_method?: string | null
          created_at?: string
          entity_type: string
          full_sync_cron?: string | null
          id?: number
          incremental_sync_cron?: string | null
          is_active?: boolean
          refresh_mode: string
          source_connector_id?: number | null
          staleness_days?: number | null
          updated_at?: string
        }
        Update: {
          change_detection_method?: string | null
          created_at?: string
          entity_type?: string
          full_sync_cron?: string | null
          id?: number
          incremental_sync_cron?: string | null
          is_active?: boolean
          refresh_mode?: string
          source_connector_id?: number | null
          staleness_days?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "refresh_policies_source_connector_id_fkey"
            columns: ["source_connector_id"]
            isOneToOne: false
            referencedRelation: "source_connectors"
            referencedColumns: ["id"]
          },
        ]
      }
      regulatory_statuses: {
        Row: {
          authority_name: string | null
          country_code: string
          created_at: string
          effective_date: string | null
          expiry_date: string | null
          id: number
          ingredient_id: number
          notes: string | null
          reference_number: string | null
          reference_url: string | null
          regulatory_category: string
          status: string
          updated_at: string
        }
        Insert: {
          authority_name?: string | null
          country_code: string
          created_at?: string
          effective_date?: string | null
          expiry_date?: string | null
          id?: number
          ingredient_id: number
          notes?: string | null
          reference_number?: string | null
          reference_url?: string | null
          regulatory_category: string
          status: string
          updated_at?: string
        }
        Update: {
          authority_name?: string | null
          country_code?: string
          created_at?: string
          effective_date?: string | null
          expiry_date?: string | null
          id?: number
          ingredient_id?: number
          notes?: string | null
          reference_number?: string | null
          reference_url?: string | null
          regulatory_category?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "regulatory_statuses_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      review_tasks: {
        Row: {
          assigned_role: string | null
          assigned_to: string | null
          auto_check_details: Json | null
          auto_check_passed: boolean | null
          created_at: string
          due_at: string | null
          entity_id: number
          entity_type: string
          id: number
          parent_task_id: number | null
          priority: string | null
          rejection_reason: string | null
          review_level: string
          reviewed_at: string | null
          reviewer_comment: string | null
          status: string
          task_type: string
          updated_at: string
        }
        Insert: {
          assigned_role?: string | null
          assigned_to?: string | null
          auto_check_details?: Json | null
          auto_check_passed?: boolean | null
          created_at?: string
          due_at?: string | null
          entity_id: number
          entity_type: string
          id?: number
          parent_task_id?: number | null
          priority?: string | null
          rejection_reason?: string | null
          review_level?: string
          reviewed_at?: string | null
          reviewer_comment?: string | null
          status?: string
          task_type: string
          updated_at?: string
        }
        Update: {
          assigned_role?: string | null
          assigned_to?: string | null
          auto_check_details?: Json | null
          auto_check_passed?: boolean | null
          created_at?: string
          due_at?: string | null
          entity_id?: number
          entity_type?: string
          id?: number
          parent_task_id?: number | null
          priority?: string | null
          rejection_reason?: string | null
          review_level?: string
          reviewed_at?: string | null
          reviewer_comment?: string | null
          status?: string
          task_type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_tasks_parent_task_id_fkey"
            columns: ["parent_task_id"]
            isOneToOne: false
            referencedRelation: "review_tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      revision_histories: {
        Row: {
          change_reason: string | null
          change_type: string | null
          changed_by: string | null
          created_at: string
          entity_id: number
          entity_type: string
          field_name: string | null
          id: number
          new_value: string | null
          old_value: string | null
        }
        Insert: {
          change_reason?: string | null
          change_type?: string | null
          changed_by?: string | null
          created_at?: string
          entity_id: number
          entity_type: string
          field_name?: string | null
          id?: number
          new_value?: string | null
          old_value?: string | null
        }
        Update: {
          change_reason?: string | null
          change_type?: string | null
          changed_by?: string | null
          created_at?: string
          entity_id?: number
          entity_type?: string
          field_name?: string | null
          id?: number
          new_value?: string | null
          old_value?: string | null
        }
        Relationships: []
      }
      safety_items: {
        Row: {
          applies_to_population: string | null
          created_at: string
          description: string
          evidence_level: string | null
          frequency_text: string | null
          id: number
          ingredient_id: number
          management_advice: string | null
          safety_type: string
          severity_level: string | null
          title: string
          updated_at: string
        }
        Insert: {
          applies_to_population?: string | null
          created_at?: string
          description: string
          evidence_level?: string | null
          frequency_text?: string | null
          id?: number
          ingredient_id: number
          management_advice?: string | null
          safety_type: string
          severity_level?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          applies_to_population?: string | null
          created_at?: string
          description?: string
          evidence_level?: string | null
          frequency_text?: string | null
          id?: number
          ingredient_id?: number
          management_advice?: string | null
          safety_type?: string
          severity_level?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "safety_items_ingredient_id_fkey"
            columns: ["ingredient_id"]
            isOneToOne: false
            referencedRelation: "ingredients"
            referencedColumns: ["id"]
          },
        ]
      }
      scan_events: {
        Row: {
          created_at: string
          detected_barcode: string | null
          extracted_name: string | null
          id: number
          image_sha256: string | null
          latency_ms: number | null
          match_confidence: number | null
          matched_product_id: number | null
          model_used: string | null
          tier_hit: string
        }
        Insert: {
          created_at?: string
          detected_barcode?: string | null
          extracted_name?: string | null
          id?: number
          image_sha256?: string | null
          latency_ms?: number | null
          match_confidence?: number | null
          matched_product_id?: number | null
          model_used?: string | null
          tier_hit: string
        }
        Update: {
          created_at?: string
          detected_barcode?: string | null
          extracted_name?: string | null
          id?: number
          image_sha256?: string | null
          latency_ms?: number | null
          match_confidence?: number | null
          matched_product_id?: number | null
          model_used?: string | null
          tier_hit?: string
        }
        Relationships: [
          {
            foreignKeyName: "scan_events_matched_product_id_fkey"
            columns: ["matched_product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      scrape_jobs: {
        Row: {
          attempts: number
          completed_at: string | null
          created_at: string
          id: number
          last_error: string | null
          result_summary: Json | null
          scheduled_for: string
          source: string
          started_at: string | null
          status: string
          target_id: number
          target_query: string | null
          target_type: string
          updated_at: string
        }
        Insert: {
          attempts?: number
          completed_at?: string | null
          created_at?: string
          id?: number
          last_error?: string | null
          result_summary?: Json | null
          scheduled_for?: string
          source: string
          started_at?: string | null
          status?: string
          target_id: number
          target_query?: string | null
          target_type: string
          updated_at?: string
        }
        Update: {
          attempts?: number
          completed_at?: string | null
          created_at?: string
          id?: number
          last_error?: string | null
          result_summary?: Json | null
          scheduled_for?: string
          source?: string
          started_at?: string | null
          status?: string
          target_id?: number
          target_query?: string | null
          target_type?: string
          updated_at?: string
        }
        Relationships: []
      }
      source_connectors: {
        Row: {
          access_strategy: string
          auth_type: string | null
          base_url: string | null
          connector_name: string
          created_at: string
          id: number
          is_active: boolean
          parser_config: Json | null
          rate_limit_per_minute: number | null
          retry_policy: Json | null
          schedule_policy: Json | null
          source_category: string
          source_id: number
          updated_at: string
        }
        Insert: {
          access_strategy: string
          auth_type?: string | null
          base_url?: string | null
          connector_name: string
          created_at?: string
          id?: number
          is_active?: boolean
          parser_config?: Json | null
          rate_limit_per_minute?: number | null
          retry_policy?: Json | null
          schedule_policy?: Json | null
          source_category: string
          source_id: number
          updated_at?: string
        }
        Update: {
          access_strategy?: string
          auth_type?: string | null
          base_url?: string | null
          connector_name?: string
          created_at?: string
          id?: number
          is_active?: boolean
          parser_config?: Json | null
          rate_limit_per_minute?: number | null
          retry_policy?: Json | null
          schedule_policy?: Json | null
          source_category?: string
          source_id?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "source_connectors_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      source_links: {
        Row: {
          created_at: string
          entity_id: number
          entity_type: string
          id: number
          retrieved_at: string | null
          source_excerpt: string | null
          source_id: number
          source_reference: string | null
        }
        Insert: {
          created_at?: string
          entity_id: number
          entity_type: string
          id?: number
          retrieved_at?: string | null
          source_excerpt?: string | null
          source_id: number
          source_reference?: string | null
        }
        Update: {
          created_at?: string
          entity_id?: number
          entity_type?: string
          id?: number
          retrieved_at?: string | null
          source_excerpt?: string | null
          source_id?: number
          source_reference?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "source_links_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          access_method: string | null
          country_code: string | null
          created_at: string
          id: number
          notes: string | null
          organization_name: string | null
          source_name: string
          source_type: string
          source_url: string | null
          trust_level: string | null
          updated_at: string
        }
        Insert: {
          access_method?: string | null
          country_code?: string | null
          created_at?: string
          id?: number
          notes?: string | null
          organization_name?: string | null
          source_name: string
          source_type: string
          source_url?: string | null
          trust_level?: string | null
          updated_at?: string
        }
        Update: {
          access_method?: string | null
          country_code?: string | null
          created_at?: string
          id?: number
          notes?: string | null
          organization_name?: string | null
          source_name?: string
          source_type?: string
          source_url?: string | null
          trust_level?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      staging_regulatory_standards_kr: {
        Row: {
          id: number
          import_batch: string | null
          imported_at: string
          injury_flag: string | null
          max_value: string | null
          min_value: string | null
          product_code: string | null
          source_dataset: string
          source_text: string | null
          test_name_ko: string
          unit: string | null
          updated_at: string
          valid_end_date: string | null
          valid_start_date: string | null
        }
        Insert: {
          id?: number
          import_batch?: string | null
          imported_at?: string
          injury_flag?: string | null
          max_value?: string | null
          min_value?: string | null
          product_code?: string | null
          source_dataset: string
          source_text?: string | null
          test_name_ko: string
          unit?: string | null
          updated_at?: string
          valid_end_date?: string | null
          valid_start_date?: string | null
        }
        Update: {
          id?: number
          import_batch?: string | null
          imported_at?: string
          injury_flag?: string | null
          max_value?: string | null
          min_value?: string | null
          product_code?: string | null
          source_dataset?: string
          source_text?: string | null
          test_name_ko?: string
          unit?: string | null
          updated_at?: string
          valid_end_date?: string | null
          valid_start_date?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      scan_events_weekly: {
        Row: {
          avg_conf: number | null
          avg_ms: number | null
          day: string | null
          miss_rate: number | null
          n: number | null
          tier_hit: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
      is_reviewer: { Args: never; Returns: boolean }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
